-- Seed Services (Identity Documents Category)
INSERT INTO services (name, name_urdu, slug, description, description_urdu, category_id, department, requirements, fees, processing_time, urgency_options, how_to_apply, how_to_apply_urdu, online_portal_url, is_online_available, tracking_info) VALUES

-- CNIC Services
('CNIC New Registration', 'نیا شناختی کارڈ', 'cnic-new-registration', 'Apply for a new Computerized National Identity Card for Pakistani citizens aged 18 and above', 'اٹھارہ سال اور اس سے زیادہ عمر کے پاکستانی شہریوں کے لیے نیا کمپیوٹرائزڈ قومی شناختی کارڈ', (SELECT id FROM service_categories WHERE slug = 'identity-documents'), 'NADRA',
'[{"text": "Original B-Form or Family Registration Certificate", "text_urdu": "اصل بی فارم یا خاندانی رجسٹریشن سرٹیفکیٹ", "type": "document"}, {"text": "Two recent passport-size photographs", "text_urdu": "دو حالیہ پاسپورٹ سائز تصاویر", "type": "document"}, {"text": "Proof of address (utility bill, rent agreement)", "text_urdu": "پتے کا ثبوت (یوٹیلیٹی بل، کرایہ کا معاہدہ)", "type": "document"}]'::jsonb,
'{"normal": 250, "urgent": 1000, "executive": 2500, "currency": "PKR"}'::jsonb,
'7-10 days',
'[{"type": "normal", "days": 10, "fee": 250}, {"type": "urgent", "days": 3, "fee": 1000}, {"type": "executive", "days": 1, "fee": 2500}]'::jsonb,
'Visit nearest NADRA office with required documents. Fill application form, provide biometric data, and pay fee.',
'مطلوبہ دستاویزات کے ساتھ قریبی نادرا دفتر جائیں۔ درخواست فارم بھریں، بائیو میٹرک ڈیٹا فراہم کریں اور فیس ادا کریں۔',
'https://id.nadra.gov.pk',
true,
'{"url": "https://id.nadra.gov.pk/track-application", "required_fields": ["tracking_id", "cnic_number"]}'::jsonb),

('CNIC Renewal', 'شناختی کارڈ کی تجدید', 'cnic-renewal', 'Renew your expired or expiring Computerized National Identity Card', 'اپنے میعاد ختم یا ختم ہونے والے کمپیوٹرائزڈ قومی شناختی کارڈ کی تجدید کریں', (SELECT id FROM service_categories WHERE slug = 'identity-documents'), 'NADRA',
'[{"text": "Original expired CNIC", "text_urdu": "اصل میعاد ختم شدہ شناختی کارڈ", "type": "document"}, {"text": "Two recent passport-size photographs", "text_urdu": "دو حالیہ پاسپورٹ سائز تصاویر", "type": "document"}]'::jsonb,
'{"normal": 250, "urgent": 1000, "executive": 2500, "currency": "PKR"}'::jsonb,
'7-10 days',
'[{"type": "normal", "days": 10, "fee": 250}, {"type": "urgent", "days": 3, "fee": 1000}, {"type": "executive", "days": 1, "fee": 2500}]'::jsonb,
'Visit NADRA office with expired CNIC. Update biometric data if required and pay renewal fee.',
'میعاد ختم شدہ شناختی کارڈ کے ساتھ نادرا دفتر جائیں۔ اگر ضرورت ہو تو بائیو میٹرک ڈیٹا اپ ڈیٹ کریں اور تجدید کی فیس ادا کریں۔',
'https://id.nadra.gov.pk',
true,
'{"url": "https://id.nadra.gov.pk/track-application", "required_fields": ["tracking_id", "cnic_number"]}'::jsonb),

('CNIC Modification', 'شناختی کارڈ میں تبدیلی', 'cnic-modification', 'Modify information on your CNIC such as name, address, or date of birth', 'اپنے شناختی کارڈ پر معلومات میں تبدیلی جیسے نام، پتہ، یا تاریخ پیدائش', (SELECT id FROM service_categories WHERE slug = 'identity-documents'), 'NADRA',
'[{"text": "Original CNIC", "text_urdu": "اصل شناختی کارڈ", "type": "document"}, {"text": "Supporting documents for modification (birth certificate, marriage certificate, etc.)", "text_urdu": "تبدیلی کے لیے معاون دستاویزات (پیدائش کا سرٹیفکیٹ، شادی کا سرٹیفکیٹ وغیرہ)", "type": "document"}, {"text": "Affidavit if required", "text_urdu": "اگر ضرورت ہو تو حلف نامہ", "type": "document"}]'::jsonb,
'{"normal": 500, "urgent": 1500, "executive": 3000, "currency": "PKR"}'::jsonb,
'10-15 days',
'[{"type": "normal", "days": 15, "fee": 500}, {"type": "urgent", "days": 5, "fee": 1500}, {"type": "executive", "days": 2, "fee": 3000}]'::jsonb,
'Visit NADRA office with supporting documents. Submit modification request and pay fee.',
'معاون دستاویزات کے ساتھ نادرا دفتر جائیں۔ تبدیلی کی درخواست جمع کرائیں اور فیس ادا کریں۔',
'https://id.nadra.gov.pk',
true,
'{"url": "https://id.nadra.gov.pk/track-application", "required_fields": ["tracking_id", "cnic_number"]}'::jsonb),

-- Passport Services
('New Passport (36 Pages)', 'نیا پاسپورٹ (36 صفحات)', 'new-passport-36', 'Apply for a new Pakistani passport with 36 pages validity for 5 years', 'پانچ سال کی میعاد کے ساتھ 36 صفحات والا نیا پاکستانی پاسپورٹ', (SELECT id FROM service_categories WHERE slug = 'identity-documents'), 'Directorate General of Immigration & Passports',
'[{"text": "Original CNIC", "text_urdu": "اصل شناختی کارڈ", "type": "document"}, {"text": "CNIC photocopy", "text_urdu": "شناختی کارڈ کی فوٹو کاپی", "type": "document"}, {"text": "Four recent passport-size photographs", "text_urdu": "چار حالیہ پاسپورٹ سائز تصاویر", "type": "document"}, {"text": "Fee payment receipt", "text_urdu": "فیس ادائیگی کی رسید", "type": "document"}]'::jsonb,
'{"normal": 3000, "urgent": 5000, "fast_track": 9000, "currency": "PKR"}'::jsonb,
'10-12 working days',
'[{"type": "normal", "days": 12, "fee": 3000}, {"type": "urgent", "days": 5, "fee": 5000}, {"type": "fast_track", "days": 2, "fee": 9000}]'::jsonb,
'Apply online at passport.gov.pk, pay fee at designated bank, visit passport office for biometric verification.',
'passport.gov.pk پر آن لائن درخواست دیں، نامزد بینک میں فیس ادا کریں، بائیو میٹرک تصدیق کے لیے پاسپورٹ آفس جائیں۔',
'https://passport.gov.pk',
true,
'{"url": "https://passport.gov.pk/track", "required_fields": ["tracking_id", "cnic_number"]}'::jsonb),

('New Passport (72 Pages)', 'نیا پاسپورٹ (72 صفحات)', 'new-passport-72', 'Apply for a new Pakistani passport with 72 pages validity for 10 years', 'دس سال کی میعاد کے ساتھ 72 صفحات والا نیا پاکستانی پاسپورٹ', (SELECT id FROM service_categories WHERE slug = 'identity-documents'), 'Directorate General of Immigration & Passports',
'[{"text": "Original CNIC", "text_urdu": "اصل شناختی کارڈ", "type": "document"}, {"text": "CNIC photocopy", "text_urdu": "شناختی کارڈ کی فوٹو کاپی", "type": "document"}, {"text": "Four recent passport-size photographs", "text_urdu": "چار حالیہ پاسپورٹ سائز تصاویر", "type": "document"}, {"text": "Fee payment receipt", "text_urdu": "فیس ادائیگی کی رسید", "type": "document"}]'::jsonb,
'{"normal": 6700, "urgent": 11200, "fast_track": 18200, "currency": "PKR"}'::jsonb,
'10-12 working days',
'[{"type": "normal", "days": 12, "fee": 6700}, {"type": "urgent", "days": 5, "fee": 11200}, {"type": "fast_track", "days": 2, "fee": 18200}]'::jsonb,
'Apply online at passport.gov.pk, pay fee at designated bank, visit passport office for biometric verification.',
'passport.gov.pk پر آن لائن درخواست دیں، نامزد بینک میں فیس ادا کریں، بائیو میٹرک تصدیق کے لیے پاسپورٹ آفس جائیں۔',
'https://passport.gov.pk',
true,
'{"url": "https://passport.gov.pk/track", "required_fields": ["tracking_id", "cnic_number"]}'::jsonb),

('Passport Renewal', 'پاسپورٹ کی تجدید', 'passport-renewal', 'Renew your expired or expiring Pakistani passport', 'اپنے میعاد ختم یا ختم ہونے والے پاکستانی پاسپورٹ کی تجدید کریں', (SELECT id FROM service_categories WHERE slug = 'identity-documents'), 'Directorate General of Immigration & Passports',
'[{"text": "Original expired passport", "text_urdu": "اصل میعاد ختم شدہ پاسپورٹ", "type": "document"}, {"text": "Original CNIC", "text_urdu": "اصل شناختی کارڈ", "type": "document"}, {"text": "Four recent passport-size photographs", "text_urdu": "چار حالیہ پاسپورٹ سائز تصاویر", "type": "document"}]'::jsonb,
'{"normal_36": 4500, "urgent_36": 7500, "normal_72": 8200, "urgent_72": 13700, "currency": "PKR"}'::jsonb,
'10-12 working days',
'[{"type": "normal", "days": 12, "fee": 4500}, {"type": "urgent", "days": 5, "fee": 7500}]'::jsonb,
'Apply online, pay fee, visit passport office with old passport and CNIC.',
'آن لائن درخواست دیں، فیس ادا کریں، پرانے پاسپورٹ اور شناختی کارڈ کے ساتھ پاسپورٹ آفس جائیں۔',
'https://passport.gov.pk',
true,
'{"url": "https://passport.gov.pk/track", "required_fields": ["tracking_id", "cnic_number"]}'::jsonb),

-- Birth Certificate
('Birth Certificate (NADRA)', 'پیدائش کا سرٹیفکیٹ', 'birth-certificate', 'Obtain computerized birth certificate from NADRA', 'نادرا سے کمپیوٹرائزڈ پیدائش کا سرٹیفکیٹ حاصل کریں', (SELECT id FROM service_categories WHERE slug = 'identity-documents'), 'NADRA',
'[{"text": "Hospital birth certificate or Union Council certificate", "text_urdu": "ہسپتال کا پیدائش کا سرٹیفکیٹ یا یونین کونسل کا سرٹیفکیٹ", "type": "document"}, {"text": "Parents CNICs", "text_urdu": "والدین کے شناختی کارڈ", "type": "document"}, {"text": "Child vaccination card (if available)", "text_urdu": "بچے کا ویکسینیشن کارڈ (اگر دستیاب ہو)", "type": "document"}]'::jsonb,
'{"normal": 200, "urgent": 700, "currency": "PKR"}'::jsonb,
'5-7 days',
'[{"type": "normal", "days": 7, "fee": 200}, {"type": "urgent", "days": 2, "fee": 700}]'::jsonb,
'Visit NADRA office with hospital certificate and parents CNICs. Fill form and pay fee.',
'ہسپتال کے سرٹیفکیٹ اور والدین کے شناختی کارڈوں کے ساتھ نادرا دفتر جائیں۔ فارم بھریں اور فیس ادا کریں۔',
'https://id.nadra.gov.pk',
true,
null),

('Death Certificate (NADRA)', 'موت کا سرٹیفکیٹ', 'death-certificate', 'Obtain computerized death certificate from NADRA', 'نادرا سے کمپیوٹرائزڈ موت کا سرٹیفکیٹ حاصل کریں', (SELECT id FROM service_categories WHERE slug = 'identity-documents'), 'NADRA',
'[{"text": "Hospital death certificate or Union Council certificate", "text_urdu": "ہسپتال کا موت کا سرٹیفکیٹ یا یونین کونسل کا سرٹیفکیٹ", "type": "document"}, {"text": "Deceased CNIC", "text_urdu": "مرحوم کا شناختی کارڈ", "type": "document"}, {"text": "Applicant CNIC (next of kin)", "text_urdu": "درخواست گزار کا شناختی کارڈ (قریبی رشتہ دار)", "type": "document"}]'::jsonb,
'{"normal": 200, "urgent": 700, "currency": "PKR"}'::jsonb,
'5-7 days',
'[{"type": "normal", "days": 7, "fee": 200}, {"type": "urgent", "days": 2, "fee": 700}]'::jsonb,
'Visit NADRA office with death certificate and required documents. Fill form and pay fee.',
'موت کے سرٹیفکیٹ اور مطلوبہ دستاویزات کے ساتھ نادرا دفتر جائیں۔ فارم بھریں اور فیس ادا کریں۔',
'https://id.nadra.gov.pk',
true,
null),

('Marriage Certificate (NADRA)', 'شادی کا سرٹیفکیٹ', 'marriage-certificate', 'Obtain computerized marriage certificate from NADRA', 'نادرا سے کمپیوٹرائزڈ شادی کا سرٹیفکیٹ حاصل کریں', (SELECT id FROM service_categories WHERE slug = 'identity-documents'), 'NADRA',
'[{"text": "Nikah Nama (marriage contract)", "text_urdu": "نکاح نامہ", "type": "document"}, {"text": "CNICs of both spouses", "text_urdu": "دونوں شریک حیات کے شناختی کارڈ", "type": "document"}, {"text": "Two witnesses CNICs", "text_urdu": "دو گواہوں کے شناختی کارڈ", "type": "document"}]'::jsonb,
'{"normal": 300, "urgent": 800, "currency": "PKR"}'::jsonb,
'5-7 days',
'[{"type": "normal", "days": 7, "fee": 300}, {"type": "urgent", "days": 2, "fee": 800}]'::jsonb,
'Visit NADRA office with Nikah Nama and CNICs. Fill application form and pay fee.',
'نکاح نامے اور شناختی کارڈوں کے ساتھ نادرا دفتر جائیں۔ درخواست فارم بھریں اور فیس ادا کریں۔',
'https://id.nadra.gov.pk',
true,
null);
