-- Seed Services (Vehicle Services Category)
INSERT INTO services (name, name_urdu, slug, description, description_urdu, category_id, department, requirements, fees, processing_time, urgency_options, how_to_apply, how_to_apply_urdu, online_portal_url, is_online_available) VALUES

('Driving License (Learner)', 'ڈرائیونگ لائسنس (سیکھنے والا)', 'driving-license-learner', 'Apply for learner driving license to practice driving', 'ڈرائیونگ کی مشق کے لیے سیکھنے والے کا ڈرائیونگ لائسنس', (SELECT id FROM service_categories WHERE slug = 'vehicle-services'), 'Excise & Taxation Department',
'[{"text": "Original CNIC", "text_urdu": "اصل شناختی کارڈ", "type": "document"}, {"text": "CNIC photocopy", "text_urdu": "شناختی کارڈ کی فوٹو کاپی", "type": "document"}, {"text": "Four passport-size photographs", "text_urdu": "چار پاسپورٹ سائز تصاویر", "type": "document"}, {"text": "Medical fitness certificate", "text_urdu": "طبی تندرستی کا سرٹیفکیٹ", "type": "document"}]'::jsonb,
'{"application": 200, "test": 100, "license": 500, "total": 800, "currency": "PKR"}'::jsonb,
'Same day after test',
null,
'Visit Excise office, submit documents, pass written test, pay fee and get learner permit.',
'ایکسائز آفس جائیں، دستاویزات جمع کرائیں، تحریری ٹیسٹ پاس کریں، فیس ادا کریں اور سیکھنے والے کا پرمٹ حاصل کریں۔',
null,
false),

('Driving License (Permanent)', 'ڈرائیونگ لائسنس (مستقل)', 'driving-license-permanent', 'Apply for permanent driving license after completing learner period', 'سیکھنے کی مدت مکمل کرنے کے بعد مستقل ڈرائیونگ لائسنس کے لیے درخواست دیں', (SELECT id FROM service_categories WHERE slug = 'vehicle-services'), 'Excise & Taxation Department',
'[{"text": "Learner permit (minimum 42 days old)", "text_urdu": "سیکھنے والے کا پرمٹ (کم از کم 42 دن پرانا)", "type": "document"}, {"text": "Original CNIC", "text_urdu": "اصل شناختی کارڈ", "type": "document"}, {"text": "Medical fitness certificate", "text_urdu": "طبی تندرستی کا سرٹیفکیٹ", "type": "document"}, {"text": "Four passport-size photographs", "text_urdu": "چار پاسپورٹ سائز تصاویر", "type": "document"}]'::jsonb,
'{"test": 300, "license_5yr": 2000, "license_10yr": 3000, "currency": "PKR"}'::jsonb,
'7-10 days after test',
null,
'Pass practical driving test at Excise office, submit documents and fee, receive permanent license.',
'ایکسائز آفس میں عملی ڈرائیونگ ٹیسٹ پاس کریں، دستاویزات اور فیس جمع کرائیں، مستقل لائسنس حاصل کریں۔',
null,
false),

('Driving License Renewal', 'ڈرائیونگ لائسنس کی تجدید', 'driving-license-renewal', 'Renew your expired or expiring driving license', 'اپنے میعاد ختم یا ختم ہونے والے ڈرائیونگ لائسنس کی تجدید کریں', (SELECT id FROM service_categories WHERE slug = 'vehicle-services'), 'Excise & Taxation Department',
'[{"text": "Original expired license", "text_urdu": "اصل میعاد ختم شدہ لائسنس", "type": "document"}, {"text": "Original CNIC", "text_urdu": "اصل شناختی کارڈ", "type": "document"}, {"text": "Medical fitness certificate", "text_urdu": "طبی تندرستی کا سرٹیفکیٹ", "type": "document"}, {"text": "Two passport-size photographs", "text_urdu": "دو پاسپورٹ سائز تصاویر", "type": "document"}]'::jsonb,
'{"renewal_5yr": 2000, "renewal_10yr": 3000, "currency": "PKR"}'::jsonb,
'5-7 days',
null,
'Visit Excise office with old license and documents. Pay renewal fee and get new license.',
'پرانے لائسنس اور دستاویزات کے ساتھ ایکسائز آفس جائیں۔ تجدید کی فیس ادا کریں اور نیا لائسنس حاصل کریں۔',
null,
false),

('Vehicle Registration (New)', 'گاڑی کی رجسٹریشن (نئی)', 'vehicle-registration-new', 'Register a new vehicle and obtain registration number', 'نئی گاڑی کی رجسٹریشن کریں اور رجسٹریشن نمبر حاصل کریں', (SELECT id FROM service_categories WHERE slug = 'vehicle-services'), 'Excise & Taxation Department',
'[{"text": "Original invoice from dealer", "text_urdu": "ڈیلر سے اصل انوائس", "type": "document"}, {"text": "Original CNIC", "text_urdu": "اصل شناختی کارڈ", "type": "document"}, {"text": "Insurance certificate", "text_urdu": "انشورنس سرٹیفکیٹ", "type": "document"}, {"text": "Computerized registration form", "text_urdu": "کمپیوٹرائزڈ رجسٹریشن فارم", "type": "document"}]'::jsonb,
'{"registration": 5000, "number_plate": 1500, "token_tax": 0, "currency": "PKR", "note": "Token tax varies by engine capacity"}'::jsonb,
'3-5 days',
null,
'Submit documents at Excise office, pay registration fee and token tax, receive number plates.',
'ایکسائز آفس میں دستاویزات جمع کرائیں، رجسٹریشن فیس اور ٹوکن ٹیکس ادا کریں، نمبر پلیٹیں حاصل کریں۔',
null,
false),

('Vehicle Transfer of Ownership', 'گاڑی کی ملکیت کی منتقلی', 'vehicle-transfer-ownership', 'Transfer vehicle ownership from seller to buyer', 'بیچنے والے سے خریدار کو گاڑی کی ملکیت منتقل کریں', (SELECT id FROM service_categories WHERE slug = 'vehicle-services'), 'Excise & Taxation Department',
'[{"text": "Original registration book", "text_urdu": "اصل رجسٹریشن کتاب", "type": "document"}, {"text": "Seller and buyer CNICs", "text_urdu": "بیچنے والے اور خریدار کے شناختی کارڈ", "type": "document"}, {"text": "Sale letter on stamp paper", "text_urdu": "سٹامپ پیپر پر فروخت کا خط", "type": "document"}, {"text": "Token tax clearance", "text_urdu": "ٹوکن ٹیکس کی ادائیگی", "type": "document"}]'::jsonb,
'{"transfer_fee": 1000, "new_registration_book": 500, "currency": "PKR"}'::jsonb,
'3-5 days',
null,
'Both parties visit Excise office with documents. Complete transfer form, pay fee, receive updated registration.',
'دونوں فریق دستاویزات کے ساتھ ایکسائز آفس جائیں۔ منتقلی کا فارم مکمل کریں، فیس ادا کریں، اپ ڈیٹ شدہ رجسٹریشن حاصل کریں۔',
null,
false),

('Token Tax Payment', 'ٹوکن ٹیکس کی ادائیگی', 'token-tax-payment', 'Pay annual vehicle token tax', 'سالانہ گاڑی کا ٹوکن ٹیکس ادا کریں', (SELECT id FROM service_categories WHERE slug = 'vehicle-services'), 'Excise & Taxation Department',
'[{"text": "Original registration book", "text_urdu": "اصل رجسٹریشن کتاب", "type": "document"}, {"text": "CNIC photocopy", "text_urdu": "شناختی کارڈ کی فوٹو کاپی", "type": "document"}, {"text": "Previous token tax receipt", "text_urdu": "پچھلے ٹوکن ٹیکس کی رسید", "type": "document"}]'::jsonb,
'{"varies_by_engine": true, "800cc": 1200, "1000cc": 2000, "1300cc": 3500, "1600cc": 5000, "currency": "PKR"}'::jsonb,
'Same day',
null,
'Visit Excise office or authorized bank, pay token tax based on engine capacity, get receipt.',
'ایکسائز آفس یا مجاز بینک جائیں، انجن کی صلاحیت کی بنیاد پر ٹوکن ٹیکس ادا کریں، رسید حاصل کریں۔',
null,
false),

('Duplicate Registration Book', 'ڈپلیکیٹ رجسٹریشن کتاب', 'duplicate-registration-book', 'Get duplicate registration book if original is lost or damaged', 'اگر اصل گم یا خراب ہو تو ڈپلیکیٹ رجسٹریشن کتاب حاصل کریں', (SELECT id FROM service_categories WHERE slug = 'vehicle-services'), 'Excise & Taxation Department',
'[{"text": "FIR for lost registration book", "text_urdu": "گمشدہ رجسٹریشن کتاب کے لیے ایف آئی آر", "type": "document"}, {"text": "Original CNIC", "text_urdu": "اصل شناختی کارڈ", "type": "document"}, {"text": "Vehicle verification report", "text_urdu": "گاڑی کی تصدیق کی رپورٹ", "type": "document"}, {"text": "Affidavit on stamp paper", "text_urdu": "سٹامپ پیپر پر حلف نامہ", "type": "document"}]'::jsonb,
'{"duplicate_book": 1000, "verification": 500, "currency": "PKR"}'::jsonb,
'7-10 days',
null,
'File FIR, get vehicle verified, submit documents at Excise office with fee.',
'ایف آئی آر درج کرائیں، گاڑی کی تصدیق کرائیں، فیس کے ساتھ ایکسائز آفس میں دستاویزات جمع کرائیں۔',
null,
false),

('International Driving Permit', 'بین الاقوامی ڈرائیونگ پرمٹ', 'international-driving-permit', 'Obtain international driving permit for driving abroad', 'بیرون ملک ڈرائیونگ کے لیے بین الاقوامی ڈرائیونگ پرمٹ حاصل کریں', (SELECT id FROM service_categories WHERE slug = 'vehicle-services'), 'Automobile Association of Pakistan',
'[{"text": "Valid Pakistani driving license", "text_urdu": "درست پاکستانی ڈرائیونگ لائسنس", "type": "document"}, {"text": "Original CNIC", "text_urdu": "اصل شناختی کارڈ", "type": "document"}, {"text": "Passport copy", "text_urdu": "پاسپورٹ کی کاپی", "type": "document"}, {"text": "Two passport-size photographs", "text_urdu": "دو پاسپورٹ سائز تصاویر", "type": "document"}]'::jsonb,
'{"permit_fee": 3000, "processing": 500, "currency": "PKR"}'::jsonb,
'3-5 days',
null,
'Visit AA Pakistan office with documents. Fill application form, pay fee, receive IDP.',
'دستاویزات کے ساتھ اے اے پاکستان آفس جائیں۔ درخواست فارم بھریں، فیس ادا کریں، آئی ڈی پی حاصل کریں۔',
'https://www.aapakistan.com',
false);
