-- Seed Services (Business Registration & Education)
INSERT INTO services (name, name_urdu, slug, description, description_urdu, category_id, department, requirements, fees, processing_time, how_to_apply, how_to_apply_urdu, online_portal_url, is_online_available) VALUES

-- Business Services
('Company Registration (Pvt Ltd)', 'کمپنی کی رجسٹریشن (پرائیویٹ لمیٹڈ)', 'company-registration-pvt', 'Register a private limited company with SECP', 'ایس ای سی پی کے ساتھ پرائیویٹ لمیٹڈ کمپنی کی رجسٹریشن', (SELECT id FROM service_categories WHERE slug = 'business-registration'), 'Securities & Exchange Commission of Pakistan',
'[{"text": "Name availability certificate", "text_urdu": "نام کی دستیابی کا سرٹیفکیٹ", "type": "document"}, {"text": "Memorandum and Articles of Association", "text_urdu": "میمورنڈم اور آرٹیکلز آف ایسوسی ایشن", "type": "document"}, {"text": "Directors CNICs", "text_urdu": "ڈائریکٹرز کے شناختی کارڈ", "type": "document"}, {"text": "Registered office address proof", "text_urdu": "رجسٹرڈ دفتر کے پتے کا ثبوت", "type": "document"}]'::jsonb,
'{"name_reservation": 200, "registration_upto_500k": 5000, "registration_500k_1m": 10000, "stamp_duty": 0, "currency": "PKR"}'::jsonb,
'7-10 days',
'Apply online at SECP eServices portal, submit documents, pay fees, receive incorporation certificate.',
'ایس ای سی پی ای سروسز پورٹل پر آن لائن درخواست دیں، دستاویزات جمع کرائیں، فیس ادا کریں، انکارپوریشن سرٹیفکیٹ حاصل کریں۔',
'https://eservices.secp.gov.pk',
true),

('NTN Registration', 'این ٹی این رجسٹریشن', 'ntn-registration', 'Register for National Tax Number with FBR', 'ایف بی آر کے ساتھ نیشنل ٹیکس نمبر کے لیے رجسٹر کریں', (SELECT id FROM service_categories WHERE slug = 'business-registration'), 'Federal Board of Revenue',
'[{"text": "CNIC (for individual) or incorporation certificate (for company)", "text_urdu": "شناختی کارڈ (انفرادی کے لیے) یا انکارپوریشن سرٹیفکیٹ (کمپنی کے لیے)", "type": "document"}, {"text": "Business address proof", "text_urdu": "کاروبار کے پتے کا ثبوت", "type": "document"}, {"text": "Bank account details", "text_urdu": "بینک اکاؤنٹ کی تفصیلات", "type": "document"}]'::jsonb,
'{"registration": 0, "currency": "PKR"}'::jsonb,
'Same day (online)',
'Register online at FBR IRIS portal, fill registration form, upload documents, receive NTN.',
'ایف بی آر آئی آر آئی ایس پورٹل پر آن لائن رجسٹر کریں، رجسٹریشن فارم بھریں، دستاویزات اپ لوڈ کریں، این ٹی این حاصل کریں۔',
'https://iris.fbr.gov.pk',
true),

('Sales Tax Registration', 'سیلز ٹیکس رجسٹریشن', 'sales-tax-registration', 'Register for sales tax with FBR', 'ایف بی آر کے ساتھ سیلز ٹیکس کے لیے رجسٹر کریں', (SELECT id FROM service_categories WHERE slug = 'business-registration'), 'Federal Board of Revenue',
'[{"text": "NTN certificate", "text_urdu": "این ٹی این سرٹیفکیٹ", "type": "document"}, {"text": "Business registration documents", "text_urdu": "کاروبار کی رجسٹریشن دستاویزات", "type": "document"}, {"text": "Business premises proof", "text_urdu": "کاروباری احاطے کا ثبوت", "type": "document"}, {"text": "Bank account statement", "text_urdu": "بینک اکاؤنٹ کا بیان", "type": "document"}]'::jsonb,
'{"registration": 0, "currency": "PKR"}'::jsonb,
'3-5 days',
'Apply online at FBR portal with NTN, submit documents, receive STR certificate.',
'این ٹی این کے ساتھ ایف بی آر پورٹل پر آن لائن درخواست دیں، دستاویزات جمع کرائیں، ایس ٹی آر سرٹیفکیٹ حاصل کریں۔',
'https://iris.fbr.gov.pk',
true),

('Trademark Registration', 'ٹریڈ مارک رجسٹریشن', 'trademark-registration', 'Register trademark with Intellectual Property Organization', 'انٹلیکچوئل پراپرٹی آرگنائزیشن کے ساتھ ٹریڈ مارک رجسٹر کریں', (SELECT id FROM service_categories WHERE slug = 'business-registration'), 'Intellectual Property Organization',
'[{"text": "Trademark design/logo", "text_urdu": "ٹریڈ مارک ڈیزائن/لوگو", "type": "document"}, {"text": "Applicant CNIC or company documents", "text_urdu": "درخواست گزار کا شناختی کارڈ یا کمپنی کی دستاویزات", "type": "document"}, {"text": "Power of attorney (if using agent)", "text_urdu": "پاور آف اٹارنی (اگر ایجنٹ استعمال کر رہے ہیں)", "type": "document"}]'::jsonb,
'{"filing_fee": 5000, "examination": 2000, "registration": 3000, "currency": "PKR"}'::jsonb,
'6-12 months',
'File application at IPO, pay fees, respond to examination report, receive registration certificate.',
'آئی پی او میں درخواست دائر کریں، فیس ادا کریں، امتحانی رپورٹ کا جواب دیں، رجسٹریشن سرٹیفکیٹ حاصل کریں۔',
'https://www.ipo.gov.pk',
false),

-- Education Services
('Degree Attestation (HEC)', 'ڈگری کی تصدیق (ایچ ای سی)', 'degree-attestation-hec', 'Get your degree attested by Higher Education Commission', 'ہائر ایجوکیشن کمیشن سے اپنی ڈگری کی تصدیق کرائیں', (SELECT id FROM service_categories WHERE slug = 'education'), 'Higher Education Commission',
'[{"text": "Original degree", "text_urdu": "اصل ڈگری", "type": "document"}, {"text": "Original transcript", "text_urdu": "اصل ٹرانسکرپٹ", "type": "document"}, {"text": "CNIC copy", "text_urdu": "شناختی کارڈ کی کاپی", "type": "document"}, {"text": "Passport copy (for foreign use)", "text_urdu": "پاسپورٹ کی کاپی (غیر ملکی استعمال کے لیے)", "type": "document"}]'::jsonb,
'{"attestation_per_degree": 2000, "courier": 500, "currency": "PKR"}'::jsonb,
'10-15 days',
'Submit documents at HEC regional office or apply online, pay fee, receive attested documents.',
'ایچ ای سی علاقائی دفتر میں دستاویزات جمع کرائیں یا آن لائن درخواست دیں، فیس ادا کریں، تصدیق شدہ دستاویزات حاصل کریں۔',
'https://www.hec.gov.pk',
true),

('Degree Equivalence Certificate', 'ڈگری کی مساوات کا سرٹیفکیٹ', 'degree-equivalence', 'Get equivalence certificate for foreign degrees', 'غیر ملکی ڈگریوں کے لیے مساوات کا سرٹیفکیٹ حاصل کریں', (SELECT id FROM service_categories WHERE slug = 'education'), 'Higher Education Commission',
'[{"text": "Attested degree from issuing country", "text_urdu": "جاری کرنے والے ملک سے تصدیق شدہ ڈگری", "type": "document"}, {"text": "Attested transcripts", "text_urdu": "تصدیق شدہ ٹرانسکرپٹس", "type": "document"}, {"text": "CNIC copy", "text_urdu": "شناختی کارڈ کی کاپی", "type": "document"}, {"text": "Passport copy", "text_urdu": "پاسپورٹ کی کاپی", "type": "document"}]'::jsonb,
'{"equivalence_fee": 5000, "processing": 1000, "currency": "PKR"}'::jsonb,
'30-45 days',
'Submit attested foreign documents at HEC, pay fee, wait for verification, receive equivalence certificate.',
'ایچ ای سی میں تصدیق شدہ غیر ملکی دستاویزات جمع کرائیں، فیس ادا کریں، تصدیق کا انتظار کریں، مساوات کا سرٹیفکیٹ حاصل کریں۔',
'https://www.hec.gov.pk',
true),

('Matric/Inter Certificate Verification', 'میٹرک/انٹر سرٹیفکیٹ کی تصدیق', 'matric-inter-verification', 'Verify matric or intermediate certificates from education boards', 'تعلیمی بورڈز سے میٹرک یا انٹرمیڈیٹ سرٹیفکیٹ کی تصدیق کریں', (SELECT id FROM service_categories WHERE slug = 'education'), 'Board of Intermediate & Secondary Education',
'[{"text": "Original certificate", "text_urdu": "اصل سرٹیفکیٹ", "type": "document"}, {"text": "Original detailed marks certificate", "text_urdu": "اصل تفصیلی نمبروں کا سرٹیفکیٹ", "type": "document"}, {"text": "CNIC copy", "text_urdu": "شناختی کارڈ کی کاپی", "type": "document"}]'::jsonb,
'{"verification": 500, "attestation": 200, "currency": "PKR"}'::jsonb,
'3-5 days',
'Visit respective education board office, submit documents, pay fee, receive verified certificate.',
'متعلقہ تعلیمی بورڈ کے دفتر جائیں، دستاویزات جمع کرائیں، فیس ادا کریں، تصدیق شدہ سرٹیفکیٹ حاصل کریں۔',
null,
false),

('Character Certificate', 'کردار کا سرٹیفکیٹ', 'character-certificate', 'Obtain character certificate from educational institution', 'تعلیمی ادارے سے کردار کا سرٹیفکیٹ حاصل کریں', (SELECT id FROM service_categories WHERE slug = 'education'), 'Educational Institution',
'[{"text": "Application on institution letterhead", "text_urdu": "ادارے کے لیٹر ہیڈ پر درخواست", "type": "document"}, {"text": "CNIC copy", "text_urdu": "شناختی کارڈ کی کاپی", "type": "document"}, {"text": "Degree/certificate copy", "text_urdu": "ڈگری/سرٹیفکیٹ کی کاپی", "type": "document"}]'::jsonb,
'{"certificate": 500, "attestation": 200, "currency": "PKR"}'::jsonb,
'5-7 days',
'Apply to your educational institution, submit documents, pay fee, receive character certificate.',
'اپنے تعلیمی ادارے میں درخواست دیں، دستاویزات جمع کرائیں، فیس ادا کریں، کردار کا سرٹیفکیٹ حاصل کریں۔',
null,
false);
